### ISSUE TITLE
Add a 'compactMap'-Function to 'LoadableState'

### ISSUE THREAD

**Issue by tinora** [SwiftedMind/Processed#8]
A 'compactMap'-Function would help with scenarios like transforming an array of entries to a single entry where it is not sure whether the desired specific entry is really in the array of entries.

Assume a loadable list of points of interests:

`var pois: LoableState<[POI]>

  var aPOI: LoadableState<POI> {
      pois.compactMap { pois in 
          pois.first { $0.id == poiId }
      } 
  }  
`
This scenario comes up with respect to deep linking for instance.

**Comment by SwiftedMind** [comment]
Nice, thanks 👍
